<a href="https://colab.research.google.com/github/NavoditPawar/BasicsOfCoding/blob/master/matrix_numpy_refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Math and Numpy Refresher


# Scalars, Vectors

In [1]:
#Scalars can be int float. Eventually every object you make (vector,matrices, tensors) are eventually scalars
#to create numpy array, use ARRAY function

In [3]:
import numpy as np

In [4]:
s =  np.array(5)

In [5]:
s.shape

()

In [7]:
y = 8 + s

In [8]:
print (y)

13


In [9]:
y.shape

()

In [12]:
#to create vector, pass Array function like below
v = np.array([1,2,3])

In [13]:
v.shape

(3,)

In [16]:
x = v[1]

In [17]:
print (x)


2


In [19]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
matrix.shape

(3, 3)

#Element-wise operations in Numpy

In [26]:
#Python Way

values = [1,2,3,4,5]
for i in range(len(values)):
  values[i] += 5
print (values)

[6, 7, 8, 9, 10]


In [27]:
#Numpy Way
values = [1,2,3,4,5]
values = np.array(values) + 5
print (values)

[ 6  7  8  9 10]


In [28]:
multa = np.multiply(values,5)

In [29]:
multb = values * 5

In [30]:
print (multa , multb)

[30 35 40 45 50] [30 35 40 45 50]


In [31]:


a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [34]:
b = np.array([[3,4],[4,5]])
b

array([[3, 4],
       [4, 5]])

In [37]:
c = a + b
c

array([[4, 6],
       [7, 9]])

# Multiplication

In [38]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
n = m * 0.25
k = np.multiply(m, 0.25)
n,k

(array([[0.25, 0.5 , 0.75],
        [1.  , 1.25, 1.5 ]]), array([[0.25, 0.5 , 0.75],
        [1.  , 1.25, 1.5 ]]))

In [42]:
n*k

array([[0.0625, 0.25  , 0.5625],
       [1.    , 1.5625, 2.25  ]])

In [52]:
np.multiply(n,k)
np.matmul(n,k)

ValueError: ignored

In [46]:
a = np.array([[1,2,3,4],[4,5,6,7]])

a


array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [47]:
a.shape

(2, 4)

In [49]:
b=np.array([[1,2,3,4,5],[3,4,5,6,5],[4,5,6,7,4],[1,2,3,4,3]])
b.shape

(4, 5)

In [50]:
c= np.matmul(a,b)

In [51]:
c

array([[ 23,  33,  43,  53,  39],
       [ 50,  72,  94, 116,  90]])

In [53]:
#numpy matmul and numpy dot are same for 2 x 2


# Transpose

In [54]:
aa= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
aa.shape

(3, 4)

In [56]:
aa.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# NP QUiz



In [58]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = (inputs_minus_min)/(np.max(inputs_minus_min))

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    pass
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    pass


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
None
Multiply 2:
None
Multiply 3:
None
Mean == None
